In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Cust_Spend_Data.csv")

In [3]:
df.head()

Cust_ID       Name  Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  \
0        1   Abraham              1123            28              1   
1        2     Adela              9818            13              5   
2        3   Adelina              9824            10             10   
3        4    Adrian              3097            23              2   
4        5  Adrianna               817            28              1   

   FnV_Items  Staples_Items  
0         16             14  
1          2              5  
2          2              2  
3          8              9  
4         17             17

In [4]:
df.shape

(829, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 829 entries, 0 to 828
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Cust_ID          829 non-null    int64 
 1   Name             829 non-null    object
 2   Avg_Mthly_Spend  829 non-null    int64 
 3   No_Of_Visits     829 non-null    int64 
 4   Apparel_Items    829 non-null    int64 
 5   FnV_Items        829 non-null    int64 
 6   Staples_Items    829 non-null    int64 
dtypes: int64(6), object(1)
memory usage: 45.5+ KB


In [7]:
df.isnull().sum()

Cust_ID            0
Name               0
Avg_Mthly_Spend    0
No_Of_Visits       0
Apparel_Items      0
FnV_Items          0
Staples_Items      0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df = df.drop(['Cust_ID', 'Name'], axis = 1)
df.head()

Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  FnV_Items  Staples_Items
0             1123            28              1         16             14
1             9818            13              5          2              5
2             9824            10             10          2              2
3             3097            23              2          8              9
4              817            28              1         17             17

In [10]:
from sklearn.preprocessing import StandardScaler

In [12]:
X = StandardScaler()

In [13]:
scaled_df = X.fit_transform(df)
scaled_df

array([[-1.7896947 ,  2.32407237, -1.44109551,  2.28639713,  1.33272373],
       [ 2.44092704, -1.1127025 ,  0.50541069, -1.53502065, -0.78605994],
       [ 2.44384639, -1.80005748,  2.93854344, -1.53502065, -1.49232116],
       ...,
       [-0.14707492, -0.65446585,  0.01878414,  0.10272982,  0.15562169],
       [-0.35629486,  0.49112577,  0.01878414, -0.17022859,  0.3910421 ],
       [-0.03468002,  0.03288912,  0.50541069,  0.10272982,  0.15562169]])

In [15]:
from sklearn.cluster import KMeans

In [20]:
kmeans = KMeans(n_clusters = 2, random_state =123)
kmeans.fit(scaled_df)

labels = kmeans.labels_
labels

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [24]:
wss = kmeans.inertia_ # WSS
wss

2225.8180780994685

In [22]:
from sklearn.metrics import silhouette_score

In [23]:
sil_score = silhouette_score(scaled_df, labels)
sil_score

0.545949578588469

In [25]:
results1 = pd.DataFrame({'WSS': [wss], 'Silhouette Score': [sil_score]}, index = ['n_cluster = 2'])
results1

WSS  Silhouette Score
n_cluster = 2  2225.818078           0.54595

In [26]:
kmeans = KMeans(n_clusters = 3, random_state =123)
kmeans.fit(scaled_df)

labels = kmeans.labels_
labels

array([2, 1, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 2, 2, 0, 0, 2, 0, 1,
       1, 2, 2, 1, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2,
       1, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 0,
       0, 2, 2, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       0, 2, 2, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 1, 2,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 0, 1,
       2, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       0, 2, 1, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 2, 1, 1, 2, 2, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 2, 1, 0, 2, 0, 1, 1, 0, 2, 2, 0, 2, 2, 2, 0, 1, 2, 0, 2, 1,
       1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 2, 2, 2, 2,
       0, 2, 1, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 0, 1, 2, 0, 2, 1, 2, 2, 1,
       2, 2, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0,

In [27]:
wss = kmeans.inertia_ # WSS
wss

1074.382380298951

In [28]:
sil_score = silhouette_score(scaled_df, labels)
sil_score

0.5863370901372584

In [29]:
results2 = pd.DataFrame({'WSS': [wss], 'Silhouette Score': [sil_score]}, index = ['n_cluster = 3'])
results2

WSS  Silhouette Score
n_cluster = 3  1074.38238          0.586337

In [30]:
frames = [results1, results2]
results = pd.concat(frames)
results

WSS  Silhouette Score
n_cluster = 2  2225.818078          0.545950
n_cluster = 3  1074.382380          0.586337

In [31]:
kmeans = KMeans(n_clusters = 4, random_state =123)
kmeans.fit(scaled_df)

labels = kmeans.labels_
labels

array([1, 2, 2, 3, 1, 3, 3, 2, 3, 3, 2, 3, 2, 3, 1, 1, 1, 3, 3, 1, 3, 2,
       2, 1, 1, 2, 3, 1, 1, 1, 1, 3, 0, 0, 1, 1, 2, 0, 2, 1, 2, 1, 1, 1,
       2, 1, 2, 1, 2, 1, 3, 2, 3, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 3,
       3, 1, 1, 1, 1, 2, 3, 2, 1, 0, 2, 0, 2, 0, 2, 2, 3, 2, 1, 2, 2, 2,
       0, 3, 1, 0, 2, 0, 1, 2, 1, 2, 3, 2, 0, 1, 1, 2, 3, 1, 2, 2, 2, 1,
       2, 2, 2, 3, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 3, 2,
       1, 1, 3, 3, 0, 2, 3, 3, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       0, 1, 2, 1, 1, 3, 3, 1, 0, 2, 0, 2, 3, 1, 1, 3, 3, 2, 3, 2, 3, 2,
       2, 2, 2, 1, 2, 3, 2, 3, 3, 1, 1, 2, 2, 1, 1, 3, 3, 3, 3, 2, 3, 3,
       3, 2, 1, 2, 3, 1, 3, 2, 2, 3, 1, 1, 3, 1, 1, 1, 3, 2, 1, 3, 1, 2,
       2, 2, 0, 3, 1, 1, 2, 2, 3, 2, 1, 2, 2, 3, 2, 2, 2, 3, 1, 1, 1, 1,
       3, 1, 2, 1, 2, 1, 2, 1, 2, 3, 3, 2, 2, 0, 2, 1, 3, 1, 2, 1, 1, 2,
       3, 1, 3, 2, 2, 1, 2, 2, 2, 2, 3, 2, 0, 2, 1, 1, 2, 3, 2, 2, 2, 1,
       1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 3, 3, 2, 3,

In [32]:
wss = kmeans.inertia_ # WSS
wss

909.4495242917942

In [34]:
sil_score = silhouette_score(scaled_df, labels)
sil_score

0.4165618844036873

In [35]:
results3 = pd.DataFrame({'WSS': [wss], 'Silhouette Score': [sil_score]}, index = ['n_cluster = 4'])
results3

WSS  Silhouette Score
n_cluster = 4  909.449524          0.416562

In [36]:
frames = [results1, results2, results3]
results = pd.concat(frames)
results

WSS  Silhouette Score
n_cluster = 2  2225.818078          0.545950
n_cluster = 3  1074.382380          0.586337
n_cluster = 4   909.449524          0.416562

In [37]:
kmeans = KMeans(n_clusters = 5, random_state =123)
kmeans.fit(scaled_df)

labels = kmeans.labels_
labels

array([2, 3, 0, 1, 2, 1, 1, 3, 1, 1, 0, 1, 3, 1, 2, 2, 2, 1, 1, 2, 1, 3,
       3, 2, 2, 3, 1, 2, 2, 2, 2, 1, 4, 4, 2, 2, 0, 4, 0, 2, 3, 2, 2, 2,
       0, 2, 0, 2, 3, 2, 1, 3, 1, 2, 3, 0, 2, 2, 3, 0, 2, 2, 2, 2, 3, 1,
       1, 2, 2, 2, 2, 3, 1, 3, 2, 3, 0, 4, 3, 4, 3, 3, 1, 3, 2, 3, 3, 3,
       4, 1, 2, 4, 3, 4, 2, 0, 2, 3, 1, 0, 4, 2, 2, 3, 1, 2, 3, 0, 3, 2,
       3, 3, 3, 1, 0, 4, 0, 3, 4, 3, 3, 3, 2, 2, 3, 2, 0, 3, 2, 3, 1, 3,
       2, 2, 1, 1, 4, 3, 1, 1, 2, 2, 2, 3, 0, 2, 3, 0, 0, 0, 2, 3, 0, 0,
       4, 2, 3, 2, 2, 1, 1, 2, 4, 3, 4, 0, 1, 2, 2, 1, 1, 0, 1, 3, 1, 0,
       3, 0, 3, 2, 3, 1, 0, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1, 1, 0, 1, 1,
       1, 3, 2, 3, 1, 2, 1, 3, 0, 1, 2, 2, 1, 2, 2, 2, 1, 3, 2, 1, 2, 3,
       3, 3, 4, 1, 2, 2, 0, 3, 1, 0, 2, 3, 0, 1, 3, 0, 3, 1, 2, 2, 2, 2,
       1, 2, 0, 2, 0, 2, 3, 2, 0, 1, 1, 0, 3, 4, 0, 2, 1, 2, 3, 2, 2, 3,
       1, 2, 1, 3, 0, 2, 3, 0, 3, 3, 1, 3, 4, 3, 2, 2, 0, 1, 3, 3, 0, 2,
       2, 0, 0, 2, 3, 3, 0, 3, 2, 3, 3, 1, 1, 0, 1,

In [38]:
wss = kmeans.inertia_ # WSS
wss

813.1990732162753

In [39]:
sil_score = silhouette_score(scaled_df, labels)
sil_score

0.3933280166615459

In [40]:
results4 = pd.DataFrame({'WSS': [wss], 'Silhouette Score': [sil_score]}, index = ['n_cluster = 5'])
results4

WSS  Silhouette Score
n_cluster = 5  813.199073          0.393328

In [41]:
frames = [results1, results2, results3, results4]
results = pd.concat(frames)
results

WSS  Silhouette Score
n_cluster = 2  2225.818078          0.545950
n_cluster = 3  1074.382380          0.586337
n_cluster = 4   909.449524          0.416562
n_cluster = 5   813.199073          0.393328

### Cluster Profiling

In [49]:
kmeans = KMeans(n_clusters = 3, random_state =123)
kmeans.fit(scaled_df)

labels = kmeans.labels_
labels

array([2, 1, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 2, 2, 0, 0, 2, 0, 1,
       1, 2, 2, 1, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 2, 1, 2, 2, 2,
       1, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 0,
       0, 2, 2, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       0, 2, 2, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 1, 2,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 0, 1,
       2, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       0, 2, 1, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 2, 1, 1, 2, 2, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 2, 1, 0, 2, 0, 1, 1, 0, 2, 2, 0, 2, 2, 2, 0, 1, 2, 0, 2, 1,
       1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 2, 2, 2, 2,
       0, 2, 1, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 0, 1, 2, 0, 2, 1, 2, 2, 1,
       2, 2, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2,
       2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0,

In [50]:
df['Clust_kmeans3'] = labels

In [51]:
df['Clust_kmeans3'].value_counts()

0    584
1    139
2    106
Name: Clust_kmeans3, dtype: int64

In [52]:
df.columns

Index(['Avg_Mthly_Spend', 'No_Of_Visits', 'Apparel_Items', 'FnV_Items',
       'Staples_Items', 'Clust_kmeans3'],
      dtype='object')

In [54]:
clust_profile = df
clust_profile = clust_profile.groupby('Clust_kmeans3').mean()
clust_profile['freq'] = df['Clust_kmeans3'].value_counts().sort_index()
clust_profile

Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  FnV_Items  \
Clust_kmeans3                                                            
0                  4486.681507     17.779110       3.787671   7.351027   
1                  8604.834532     12.446043       6.935252   3.071942   
2                  1546.830189     25.377358       1.018868  15.094340   

               Staples_Items  freq  
Clust_kmeans3                       
0                   8.030822   584  
1                   3.244604   139  
2                  16.716981   106